# Generated by Django 2.1.3 on 2022-06-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=50, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Sample')),
                ('tissue', models.CharField(max_length=256, verbose_name='Tissue')),
                ('annotation', models.CharField(max_length=256, verbose_name='Annotation')),
                ('array', models.CharField(max_length=20, verbose_name='Array')),
            ],
            options={
                'verbose_name': 'Cohorts',
            },
        ),
    ]
